financials_row_mapping = {
	# INCOME STATEMENT
	'date': 'Date',
	'totalRevenue': 'Revenues',
	'costOfRevenue': 'Cost of Revenues',
	'grossProfit': 'Gross Profit',
	'otherOperatingExpenses': 'Other Operating Expenses',
	'researchDevelopment': 'Research and Development',
	'sellingAndMarketingExpenses': 'Selling and Marketing Expenses',
	'sellingGeneralAdministrative': 'Selling, General, and Administrative',
	'totalOperatingExpenses': 'Total Operating Expenses',
	'ebitda': 'EBITDA',
	'depreciationAndAmortization': 'Depreciation and Amortization',
	'ebit': 'EBIT',
	'operatingIncome': 'Operating Income',
	'interestExpense': 'Interest Expense',
	'incomeBeforeTax': 'Income Before Tax',
	'incomeTaxExpense': 'Income Tax Expense',
	'netIncome': 'Net Income',
	'minorityInterest': 'Minority Interest',
	'netIncomeApplicableToCommonShares': 'Net Inc App to Common Shares',
	'effectOfAccountingCharges': 'Effect of Accounting Charges',
	'reconciledDepreciation': 'Reconciled Depreciation',
	'nonOperatingIncomeNetOther': 'Non-Operating Income (Net Other)',
	'taxProvision': 'Tax Provision',
	'interestIncome': 'Interest Income',
	'netInterestIncome': 'Net Interest Income',
	'extraordinaryItems': 'Extraordinary Items',
	'nonRecurring': 'Non-Recurring Items',
	'otherItems': 'Other Items',
	'totalOtherIncomeExpenseNet': 'Total Other Income/Expense (Net)',
	'discontinuedOperations': 'Discontinued Operations',
	'netIncomeFromContinuingOps': 'Net Inc from Cont Operations',
	'preferredStockAndOtherAdjustments': 'Preferred Stock Adjustments',

	# CASH FLOW STATEMENT
	'changeToNetincome': 'Change to Net Income',
	'changeToOperatingActivities': 'Change to Operating Activities',
	'changeToInventory': 'Change to Inventory',
	'changeToAccountReceivables': 'Change to Account Receivables',
	'changeReceivables': 'Change Receivables',
	'cashFlowsOtherOperating': 'Cash Flows - Other Operating',
	'totalCashFromOperatingActivities': 'Total Cash from Operating Activities',
	'capitalExpenditures': 'Capital Expenditures',
	'depreciation': 'Depreciation',
	'otherCashflowsFromInvestingActivities': 'Other Investing Cash Flows',
	'totalCashflowsFromInvestingActivities': 'Total Investing Cash Flows',
	'freeCashFlow': 'Free Cash Flow',
	'issuanceOfCapitalStock': 'Issuance of Capital Stock',
	'salePurchaseOfStock': 'Sale/Purchase of Stock',
	'netBorrowings': 'Net Borrowings',
	'dividendsPaid': 'Dividends Paid',
	'exchangeRateChanges': 'Exchange Rate Changes',
	'cashAndCashEquivalentsChanges': 'Cash and Equivalents Change',
	'changeInWorkingCapital': 'Change in Working Capital',
	'stockBasedCompensation': 'Stock-Based Compensation',
	'otherNonCashItems': 'Other Non-Cash Items',
	'investments': 'Investments',
	'changeToLiabilities': 'Change to Liabilities',
	'otherCashflowsFromFinancingActivities': 'Other Financing Cash Flows',
	'totalCashFromFinancingActivities': 'Total Cash from Financing Activities',
	'beginPeriodCashFlow': 'Begin Period Cash Flow',
	'endPeriodCashFlow': 'End Period Cash Flow',
	'changeInCash': 'Change in Cash',
	# 'netIncome': 'Net Income (Cash Flow)',

	# BALANCE SHEET
	'cash': 'Cash',
	'cashAndEquivalents': 'Cash and Equivalents',
	'shortTermInvestments': 'Short-Term Investments',
	'cashAndShortTermInvestments': 'Cash and Short-Term Investments',
	'netReceivables': 'Net Receivables',
	'inventory': 'Inventory',
	'otherCurrentAssets': 'Other Current Assets',
	'totalCurrentAssets': 'Total Current Assets',
	'propertyPlantEquipment': 'Property, Plant, and Equipment',
	'propertyPlantAndEquipmentGross': 'Property, Plant, and Equipment (Gross)',
	'accumulatedDepreciation': 'Accumulated Depreciation',
	'propertyPlantAndEquipmentNet': 'Property, Plant, and Equipment (Net)',
	'longTermInvestments': 'Long-Term Investments',
	'earningAssets': 'Earning Assets',
	'intangibleAssets': 'Intangible Assets',
	'goodWill': 'Goodwill',
	'accumulatedAmortization': 'Accumulated Amortization',
	'nonCurrrentAssetsOther': 'Non-Current Assets Other',
	'nonCurrentAssetsTotal': 'Non-Current Assets Total',
	'otherAssets': 'Other Assets',
	'totalAssets': 'Total Assets',
	'shortTermDebt': 'Short-Term Debt',
	'accountsPayable': 'Accounts Payable',
	'currentDeferredRevenue': 'Current Deferred Revenue',
	'otherCurrentLiab': 'Other Current Liabilities',
	'totalCurrentLiabilities': 'Total Current Liabilities',
	'longTermDebt': 'Long-Term Debt',
	'longTermDebtTotal': 'Long-Term Debt Total',
	'capitalLeaseObligations': 'Capital Lease Obligations',
	'deferredLongTermLiab': 'Deferred Long-Term Liabilities',
	'nonCurrentLiabilitiesOther': 'Non-Current Liabilities Other',
	'nonCurrentLiabilitiesTotal': 'Non-Current Liabilities Total',
	'otherLiab': 'Other Liabilities',
	'totalLiab': 'Total Liabilities',
	'shortLongTermDebt': 'Short-Long Term Debt',
	'netTangibleAssets': 'Net Tangible Assets',
	'shortLongTermDebtTotal': 'Short-Long Term Debt Total',
	'netDebt': 'Net Debt',
	'additionalPaidInCapital': 'Additional Paid-In Capital',
	'retainedEarnings': 'Retained Earnings',
	'retainedEarningsTotalEquity': 'Retained Earnings Total Equity',
	'accumulatedOtherComprehensiveIncome': 'Acc Other Comprehensive Income',
	'otherStockholderEquity': 'Other Stockholder Equity',
	'totalPermanentEquity': 'Total Permanent Equity',
	'commonStockTotalEquity': 'Common Stock Total Equity',
	'preferredStockTotalEquity': 'Preferred Stock Total Equity',
	'totalStockholderEquity': 'Total Stockholder Equity',
	'commonStockSharesOutstanding': 'Shares Outstanding',
	'negativeGoodwill': 'Negative Goodwill',
	'warrants': 'Warrants',
	'preferredStockRedeemable': 'Preferred Stock Redeemable',
	'commonStock': 'Common Stock',
	'capitalStock': 'Capital Stock',
	'treasuryStock': 'Treasury Stock',
	'liabilitiesAndStockholdersEquity': 'Liabilities and Stockholders Equity',
	'temporaryEquityRedeemableNoncontrollingInterests': 'Temporary Equity Redeemable Noncontrolling Interests',
	'noncontrollingInterestInConsolidatedEntity': 'Noncontrolling Interest in Consolidated Entity',
	'deferredLongTermAssetCharges': 'Deferred Long-Term Asset Charges',
	'capitalSurpluse': 'Capital Surplus',
	'netWorkingCapital': 'Net Working Capital',
	'netInvestedCapital': 'Net Invested Capital',
}

share_stats_row_mappings = {
	'SharesOutstanding': 'Shares Outstanding',
	'SharesFloat': 'Shares Float',
	'PercentInsiders': 'Percent Insiders',
	'PercentInstitutions': 'Percent Institutions',
	'SharesShort': 'Shares Short',
	'SharesShortPriorMonth': 'Shares Short Prior Mnth',
	'ShortRatio': 'Short Ratio',
	'ShortPercentOutstanding': 'Short % Outstanding',
	'ShortPercentFloat': 'Short % Float'
}

earnings_estimates_row_mappings = {
	'date': 'Date',
	'period': 'Period',
	'growth': 'Growth',
	'earningsEstimateAvg': 'EPS Est Avg',
	'earningsEstimateLow': 'EPS Est Low',
	'earningsEstimateHigh': 'EPS Est High',
	'earningsEstimateYearAgoEps': 'EPS Est Year Ago EPS',
	'earningsEstimateNumberOfAnalysts': 'EPS Est Num of Analysts',
	'earningsEstimateGrowth': 'EPS Est Growth',
	'revenueEstimateAvg': 'Revenue Est Avg',
	'revenueEstimateLow': 'Revenue Est Low',
	'revenueEstimateHigh': 'Revenue Est High',
	'revenueEstimateYearAgoEps': 'Revenue Est Year Ago EPS',
	'revenueEstimateNumberOfAnalysts': 'Revenue Est Number of Analysts',
	'revenueEstimateGrowth': 'Revenue Est Growth',
	'epsTrendCurrent': 'EPS Trend Current',
	'epsTrend7daysAgo': 'EPS Trend 7 Days Ago',
	'epsTrend30daysAgo': 'EPS Trend 30 Days Ago',
	'epsTrend60daysAgo': 'EPS Trend 60 Days Ago',
	'epsTrend90daysAgo': 'EPS Trend 90 Days Ago',
	'epsRevisionsUpLast7days': 'EPS Rev Up Last 7 Days',
	'epsRevisionsUpLast30days': 'EPS Rev Up Last 30 Days',
	'epsRevisionsDownLast7days': 'EPS Rev Down Last 7 Days',
}

income_statement_order = [
	'totalRevenue',
	'costOfRevenue',
	'grossProfit',
	'otherOperatingExpenses',
	'researchDevelopment',
	'sellingAndMarketingExpenses',
	'sellingGeneralAdministrative',
	'totalOperatingExpenses',
	'ebitda',
	'depreciationAndAmortization',
	'ebit',
	'operatingIncome',
	'interestExpense',
	'incomeBeforeTax',
	'incomeTaxExpense',
	'netIncome',
	'minorityInterest',
	'netIncomeApplicableToCommonShares',
	'effectOfAccountingCharges',
	'reconciledDepreciation',
	'nonOperatingIncomeNetOther',
	'taxProvision',
	'interestIncome',
	'netInterestIncome',
	'extraordinaryItems',
	'nonRecurring',
	'otherItems',
	'totalOtherIncomeExpenseNet',
	'discontinuedOperations',
	'netIncomeFromContinuingOps',
	'preferredStockAndOtherAdjustments',
]

cash_flow_statement_order = [
	'netIncome',
	'changeToNetincome',
	'changeToOperatingActivities',
	'changeToInventory',
	'changeToAccountReceivables',
	'cashFlowsOtherOperating',
	'totalCashFromOperatingActivities',
	'capitalExpenditures',
	'depreciation',
	'otherCashflowsFromInvestingActivities',
	'totalCashflowsFromInvestingActivities',
	'freeCashFlow',
	'issuanceOfCapitalStock',
	'salePurchaseOfStock',
	'netBorrowings',
	'dividendsPaid',
	'exchangeRateChanges',
	'cashAndCashEquivalentsChanges',
	'changeInWorkingCapital',
	'stockBasedCompensation',
	'otherNonCashItems',
	'investments',
	'changeToLiabilities',
	'otherCashflowsFromFinancingActivities',
	'totalCashFromFinancingActivities',
	'beginPeriodCashFlow',
	'endPeriodCashFlow',
	'changeInCash',
]

balance_sheet_order = [
	'cash',
	'cashAndEquivalents',
	'shortTermInvestments',
	'netReceivables',
	'inventory',
	'otherCurrentAssets',
	'totalCurrentAssets',
	'propertyPlantEquipment',
	'longTermInvestments',
	'intangibleAssets',
	'goodWill',
	'nonCurrrentAssetsOther',
	'nonCurrentAssetsTotal',
	'otherAssets',
	'totalAssets',
	'shortTermDebt',
	'accountsPayable',
	'currentDeferredRevenue',
	'otherCurrentLiab',
	'totalCurrentLiabilities',
	'longTermDebt',
	'longTermDebtTotal',
	'capitalLeaseObligations',
	'deferredLongTermLiab',
	'nonCurrentLiabilitiesOther',
	'nonCurrentLiabilitiesTotal',
	'otherLiab',
	'totalLiab',
	'netTangibleAssets',
	'shortLongTermDebtTotal',
	'netDebt',
	'additionalPaidInCapital',
	'retainedEarnings',
	'accumulatedOtherComprehensiveIncome',
	'otherStockholderEquity',
	'preferredStockTotalEquity',
	'totalStockholderEquity',
	'commonStockSharesOutstanding',
	'propertyPlantAndEquipmentNet',
	'netWorkingCapital',
	'accumulatedAmortization'
]

share_stats_order = [
	'SharesOutstanding',
	'SharesFloat',
	'PercentInsiders',
	'PercentInstitutions',
	'ShortPercentOutstanding',
]

earnings_estimates_order = [
	'earningsEstimateAvg',
	'earningsEstimateGrowth',
	'earningsEstimateNumberOfAnalysts',
	'revenueEstimateAvg',
	'revenueEstimateGrowth',
	'revenueEstimateNumberOfAnalysts'
]
